USUARIOS = [
    {
        "id":1,
        "nome":"Kauan",
        "email":"kauan@gmail.com",
        'senha':'123'
    },
    {
        "id":2,
        "nome":"Maria",
        "email":"puta@gmail.com",
        'senha':'123'
    },
    {
        "id":3,
        "nome":"André",
        "email":"manoandreluizmano@gmail.com",
        'senha':'123'
    },
    {
        "id":4,
        "nome":"Thainá",
        "email":"thainadois@gmail.com",
        'senha':'123'
    },
    {
        "id":5,
        "nome":"Gustavo",
        "email":"gustavoxyz@gmail.com",
        'senha':'123'
    },
    {
        "id":6,
        "nome":"Heloísa",
        "email":"helo@gmail.com",
        'senha':'123'     
    },
    {
        "id":7,
        "nome":"Inaê",
        "email":"inae@gmail.com",
        'senha':'123'
    }
]